"use strict";
exports.__esModule = true;
exports.app = void 0;
var express_1 = require("express");
require("express-async-errors");
// import { errorHandler } from './middlewares/errorHandler';
// import { NotFoundError } from './errors/notFoundError';
// import { indexTicketRouter } from './routes';
var app = (0, express_1["default"])();
exports.app = app;
